/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPersona;
import Controlador.ControladorProducto;
import Controlador.ControladorValoresPorDefecto;

/**
 *
 * @author Alba
 */
public class VentanaSistema extends javax.swing.JFrame {

    private ControladorValoresPorDefecto ctrlVpf; //controlador de valores por defecto (IVA Y Codigo para registrar un administrador)
    private ControladorPersona ctrlPersona; //controlador de persona para sacar sus respectivos atributos
    private ControladorProducto ctrlProducto; //controlador de producto para sacar sus respectivos atributos

    /**
     * Se crea la ventana del sistema con los controladores correspondientes mostrando los valores por defecto que se tienen
     *
     * @param ctrlPersona controlador de la persona para pasarlo por su respectiva ventana
     * @param cp controlador del producto para pasarlo por su respectiva ventana
     */
    public VentanaSistema(ControladorPersona ctrlPersona, ControladorProducto cp) {
        initComponents();
        this.ctrlVpf = new ControladorValoresPorDefecto();
        this.ctrlPersona = ctrlPersona;
        this.ctrlProducto = cp;
        this.setLocationRelativeTo(null);
        btGuardar.setVisible(false);
        btGuardar.setEnabled(false);
        txtfCod.setText(ctrlVpf.getVpd().getCodigoAdmin());
        txtfIVA.setText(ctrlVpf.getVpd().getIVA().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btModificar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtfIVA = new javax.swing.JTextField();
        txtfCod = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuComprar = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();
        menuAbastecer = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        menuKardex = new javax.swing.JMenu();
        menuRegistros = new javax.swing.JMenu();
        menuSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btModificar.setBackground(new java.awt.Color(255, 255, 255));
        btModificar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btModificar.setForeground(new java.awt.Color(0, 0, 0));
        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btModificar)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModificar)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Valores por Defecto");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo Administrador: ");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("I.V.A. :");

        txtfIVA.setEditable(false);
        txtfIVA.setBackground(new java.awt.Color(255, 255, 255));
        txtfIVA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfIVA.setBorder(null);
        txtfIVA.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtfCod.setEditable(false);
        txtfCod.setBackground(new java.awt.Color(255, 255, 255));
        txtfCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfCod.setBorder(null);
        txtfCod.setSelectionColor(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfIVA, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtfCod)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 153, 255));

        menuComprar.setBackground(new java.awt.Color(51, 153, 255));
        menuComprar.setForeground(new java.awt.Color(0, 0, 0));
        menuComprar.setText("Comprar");
        menuComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComprarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuComprar);

        menuPerfil.setBackground(new java.awt.Color(51, 153, 255));
        menuPerfil.setForeground(new java.awt.Color(0, 0, 0));
        menuPerfil.setText("Perfil");
        menuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPerfilMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPerfil);

        menuAbastecer.setBackground(new java.awt.Color(51, 153, 255));
        menuAbastecer.setForeground(new java.awt.Color(0, 0, 0));
        menuAbastecer.setText("Abastecer");
        menuAbastecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbastecerMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAbastecer);

        menuProductos.setBackground(new java.awt.Color(51, 153, 255));
        menuProductos.setForeground(new java.awt.Color(0, 0, 0));
        menuProductos.setText("Productos");
        menuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProductos);

        menuKardex.setBackground(new java.awt.Color(51, 153, 255));
        menuKardex.setForeground(new java.awt.Color(0, 0, 0));
        menuKardex.setText("Kardex");
        menuKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKardexMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuKardex);

        menuRegistros.setBackground(new java.awt.Color(51, 153, 255));
        menuRegistros.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistros.setText("Registros");
        menuRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRegistros);

        menuSistema.setBackground(new java.awt.Color(51, 153, 255));
        menuSistema.setForeground(new java.awt.Color(0, 0, 0));
        menuSistema.setText("Sistema");
        menuSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSistemaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        activarEdicion(true);
    }//GEN-LAST:event_btModificarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        ctrlVpf.asignarValoresPorDefecto(Double.valueOf(txtfIVA.getText()), txtfCod.getText());
        activarEdicion(false);
    }//GEN-LAST:event_btGuardarActionPerformed

    private void menuComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComprarMouseClicked
        VentanaComprar vc = new VentanaComprar(ctrlPersona);
        this.dispose();
        vc.setVisible(true);
    }//GEN-LAST:event_menuComprarMouseClicked

    private void menuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPerfilMouseClicked
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, ctrlProducto);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuPerfilMouseClicked

    private void menuAbastecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbastecerMouseClicked
        VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, ctrlProducto);
        vtFacturarCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuAbastecerMouseClicked

    private void menuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseClicked
        VentanaProducto vp = new VentanaProducto(ctrlProducto, ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_menuProductosMouseClicked

    private void menuKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKardexMouseClicked
        VentanaKardex ventana = new VentanaKardex(ctrlProducto, ctrlPersona);
        this.dispose();
        ventana.show();
    }//GEN-LAST:event_menuKardexMouseClicked

    private void menuRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrosMouseClicked
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, ctrlProducto);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuRegistrosMouseClicked

    private void menuSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSistemaMouseClicked
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, ctrlProducto);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSistemaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSistema(new ControladorPersona(), new ControladorProducto()).setVisible(true);
            }
        });
    }

    public void activarEdicion(Boolean b) {
        txtfIVA.setEditable(b);
        txtfCod.setEditable(b);
        btGuardar.setVisible(b);
        btGuardar.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu menuAbastecer;
    private javax.swing.JMenu menuComprar;
    private javax.swing.JMenu menuKardex;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JTextField txtfCod;
    private javax.swing.JTextField txtfIVA;
    // End of variables declaration//GEN-END:variables
}
