/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorProveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author jere_
 */
public class VentanaAgregarProveedor extends javax.swing.JFrame {

    private ControladorProveedor ctrlProveedor;//ControladorProveedor usado para llamar a los metodos de este

    /**
     * Constructor usado para pasar la lista de proveedores entre la ventana facturarCompra y esta
     * @param ctrlProveedor el controladorProveedor que contiene la lista de proveedores
     */
    public VentanaAgregarProveedor(ControladorProveedor ctrlProveedor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ctrlProveedor = ctrlProveedor;
        lblRUC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btAgregarProveedor = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtfRUC = new javax.swing.JTextField();
        txtfApellido = new javax.swing.JTextField();
        txtfNombre = new javax.swing.JTextField();
        txtfDireccion = new javax.swing.JTextField();
        lblRUC = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("R.U.C");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 80, 34, 16);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 120, 49, 16);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 160, 49, 16);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direccion ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 200, 60, 16);

        btAgregarProveedor.setBackground(new java.awt.Color(51, 153, 255));
        btAgregarProveedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btAgregarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btAgregarProveedor.setText("Agregar");
        btAgregarProveedor.setBorder(null);
        btAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btAgregarProveedor);
        btAgregarProveedor.setBounds(230, 250, 75, 28);

        btCancelar.setBackground(new java.awt.Color(51, 153, 255));
        btCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.setBorder(null);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar);
        btCancelar.setBounds(70, 250, 70, 28);

        txtfRUC.setBackground(new java.awt.Color(255, 255, 255));
        txtfRUC.setBorder(null);
        txtfRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfRUCKeyTyped(evt);
            }
        });
        jPanel1.add(txtfRUC);
        txtfRUC.setBounds(170, 80, 122, 20);

        txtfApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtfApellido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfApellido.setBorder(null);
        jPanel1.add(txtfApellido);
        txtfApellido.setBounds(170, 160, 122, 20);

        txtfNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtfNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfNombre.setBorder(null);
        jPanel1.add(txtfNombre);
        txtfNombre.setBounds(170, 120, 122, 20);

        txtfDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtfDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfDireccion.setBorder(null);
        jPanel1.add(txtfDireccion);
        txtfDireccion.setBounds(170, 200, 122, 20);

        lblRUC.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        lblRUC.setForeground(new java.awt.Color(0, 0, 0));
        lblRUC.setText("Numero de R.U.C invalido");
        jPanel1.add(lblRUC);
        lblRUC.setBounds(220, 70, 106, 10);

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(-10, 10, 400, 50);

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(-10, 290, 400, 50);

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(170, 220, 120, 20);

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(170, 100, 120, 20);

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(170, 140, 120, 20);

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(170, 180, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para agregar un proveedor a la lista de proveedores y al sistema
     * @param evt Evento de tipo ActionEvent
     */
    private void btAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProveedorActionPerformed
        
        if(!lblRUC.isVisible())
        {
            String nombre = txtfNombre.getText().trim();
            String RUC = txtfRUC.getText().trim();
            String apellido = txtfApellido.getText().trim();
            String direccion = txtfDireccion.getText().trim();

            ctrlProveedor.agregarProveedor(RUC, nombre, apellido, direccion);
            this.dispose();
        }
        else
        { 
            JOptionPane.showMessageDialog(null, "Numero de RUC invalido");
        }
    }//GEN-LAST:event_btAgregarProveedorActionPerformed

    /**
     * Evento para cancelar la adicion de un nuevo proveedor y volver a la ventana anterior
     * @param evt evento de tipo ActionEvent
     */
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * Evento para validar el R.U.C del nuevo proveedor
     * @param evt evento de tipo KeyEvent
     */
    private void txtfRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfRUCKeyTyped
        if(txtfRUC.getText().length() < 12 || !ctrlProveedor.verificar_Ruc(txtfRUC.getText()))
        {
            lblRUC.setVisible(true);
        }
        else
        {
            lblRUC.setVisible(false);
            
        }
        
    }//GEN-LAST:event_txtfRUCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarProveedor(new ControladorProveedor()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarProveedor;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JTextField txtfApellido;
    private javax.swing.JTextField txtfDireccion;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfRUC;
    // End of variables declaration//GEN-END:variables
}
