/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPersona;
import Controlador.ControladorProducto;
import Controlador.ControladorProveedor;
import Controlador.EstructurasDinamicas.Lista;
import Modelo.Persona;
import Modelo.Proveedor;
import Modelo.Rol;
import Vista.ModeloTablas.ModeloTablaClienteRegistros;
import Vista.ModeloTablas.ModeloTablaProveedoresRegistro;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alba
 */
public class VentanaRegistro extends javax.swing.JDialog {

    private ControladorPersona ctrlPersona = new ControladorPersona();
    private ControladorProveedor ctrlProveedor = new ControladorProveedor();
    ModeloTablaClienteRegistros mTClienteR;
    ModeloTablaProveedoresRegistro mTProveedorR;
    ControladorProducto cp;
    
    //private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form VentanaClientes
     */
    public VentanaRegistro(java.awt.Frame parent, boolean modal, ControladorPersona ctrlPersona, ControladorProducto ctrlProducto)
    {
        super(parent, modal);
        //this.setLocationRelativeTo(null);
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbl_tabla.getModel();
        this.ctrlPersona = ctrlPersona;
        modelo.setRowCount(0);
        tbl_tabla.setModel(modelo);
        this.cp = ctrlProducto;
        jMenu5.setEnabled(false);
        jMenu5.setBackground(Color.blue);
        ctrlProveedor.setListaProveedores(ctrlProveedor.listar());
        this.setLocationRelativeTo(null);
        cbxParametro.setEnabled(false);
        txtfContenido.setEnabled(false);
    }

    private void cargarTabla() 
    {
        if(cbxRegistro.getSelectedItem().equals("Usuarios"))
        {
            mTClienteR = new ModeloTablaClienteRegistros(ctrlPersona.getPersonas());
            tbl_tabla.setModel(mTClienteR);
            tbl_tabla.updateUI();
        }    
        else
        {
            mTProveedorR = new ModeloTablaProveedoresRegistro(ctrlProveedor.getListaProveedores());
            tbl_tabla.setModel(mTProveedorR);
            tbl_tabla.updateUI();
        }
        
        cargarCBXParametros();

    }
    
    private void cargarCBXParametros()
    {
        cbxParametro.removeAllItems();
        
        for (int i = 1; i < tbl_tabla.getColumnCount(); i++)
        {
            cbxParametro.addItem(tbl_tabla.getColumnName(i));
        }
        
    }
    
    public void borrarUsuario(String identificacion) {
        
         if(cbxRegistro.getSelectedIndex() == 0){
            Lista<Persona> listaPersonas = ctrlPersona.getPersonas();
            for (int i = 0; i < listaPersonas.length(); i++) {
                if (listaPersonas.getByIndex(i).getIdentificacion().equals(identificacion)) {
                    listaPersonas.remove(i);
                    break;
                }
            }
            ctrlPersona.setPersonas(listaPersonas);
            ctrlPersona.guardarNuevaLista(listaPersonas);
            
         }else{
            Lista<Proveedor> listaProveedores = ctrlProveedor.getListaProveedores();
            for (int i = 0; i < listaProveedores.length(); i++) {
                if (listaProveedores.getByIndex(i).getRuc().equals(identificacion)) {
                    listaProveedores.remove(i);
                    break;
                }
            }
            ctrlProveedor.setListaProveedores(listaProveedores);
            ctrlProveedor.guardarNuevaLista(listaProveedores);
         }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxRegistro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxParametro = new javax.swing.JComboBox<>();
        txtfContenido = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTROS DEL SISTEMA");

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Rol", "Identificacion", "Fecha de Compra"
            }
        ));
        jScrollPane1.setViewportView(tbl_tabla);

        jLabel2.setText("Mostrar registros de:");

        cbxRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios", "Proveedores", " " }));

        jLabel3.setText("Buscar por:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_remover)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtfContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(btBuscar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_remover)
                .addGap(24, 24, 24))
        );

        jMenu1.setText("Compra");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Perfil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Abastecer");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Productos");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu4.setText("Kardex");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Registros");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu7.setText("Sistema");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
 
        try 
        {
            if (cbxParametro != null) 
            {
                if (cbxRegistro.getSelectedIndex() == 0)
                {
                    switch (cbxParametro.getSelectedIndex())
                    {
                        case 0:
                            mTClienteR = new ModeloTablaClienteRegistros(ctrlPersona.getPersonas().multipleSearch("nombres", txtfContenido.getText().trim()));
                            tbl_tabla.setModel(mTClienteR);
                            tbl_tabla.updateUI();
                            break;
                        case 1:
                            mTClienteR = new ModeloTablaClienteRegistros(ctrlPersona.getPersonas().multipleSearch("id_Rol", ctrlPersona.getRol()));
                            tbl_tabla.setModel(mTClienteR);
                            tbl_tabla.updateUI();
                            break;
                        case 2:
                            Lista<Persona> listaPersonas = new Lista();
                            listaPersonas.add(ctrlPersona.getPersonas().uniqueSearch("identificacion", txtfContenido.getText().trim(), (ctrlPersona.getPersonas().length() - 1), 0));
                            mTClienteR = new ModeloTablaClienteRegistros(listaPersonas);
                            tbl_tabla.setModel(mTClienteR);
                            tbl_tabla.updateUI();
                            break;
                        default:
                    }
                } 
                else 
                {
                    switch (cbxParametro.getSelectedIndex())
                    {
                        case 0:
                            mTProveedorR = new ModeloTablaProveedoresRegistro(ctrlProveedor.getListaProveedores().multipleSearch("nombreProveedor", txtfContenido.getText().trim()));
                            tbl_tabla.setModel(mTProveedorR);
                            tbl_tabla.updateUI();
                            break;
                        case 1:
                            Lista<Proveedor> listaProveedor = new Lista();
                            listaProveedor.add(ctrlProveedor.getListaProveedores().uniqueSearch("ruc", txtfContenido.getText().trim(), (ctrlProveedor.getListaProveedores().length() - 1), 0));
                            mTProveedorR = new ModeloTablaProveedoresRegistro(listaProveedor);
                            tbl_tabla.setModel(mTProveedorR);
                            tbl_tabla.updateUI();
                            break;
                        case 2:
                            mTProveedorR = new ModeloTablaProveedoresRegistro(ctrlProveedor.getListaProveedores().multipleSearch("direccionProveedor", txtfContenido.getText().trim()));
                            tbl_tabla.setModel(mTProveedorR);
                            tbl_tabla.updateUI();
                            break;
                        default:
                    }
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningun elemento que cumpla con las caracteristicas");
        }
        
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        Integer index = tbl_tabla.getSelectedRow();
        
        if(index == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe escoger un producto del carrito", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(cbxRegistro.getSelectedIndex() == 0){
                borrarUsuario(tbl_tabla.getValueAt(index, 3).toString());
                cargarTabla();
            }else{
                borrarUsuario(tbl_tabla.getValueAt(index, 2).toString());
                cargarTabla();
            }
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarTabla();
        cbxParametro.setEnabled(true);
        txtfContenido.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        VentanaComprar vtCompra = new VentanaComprar(ctrlPersona);
        vtCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
       VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, cp);
       vtFacturarCompra.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, cp);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        VentanaProducto vp = new VentanaProducto(cp, ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        VentanaKardex ventana = new VentanaKardex(this.cp, this.ctrlPersona);
        this.dispose();
        ventana.show();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, cp);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, cp);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistro dialog = new VentanaRegistro(new javax.swing.JFrame(), true, new ControladorPersona(), new ControladorProducto());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JComboBox<String> cbxParametro;
    private javax.swing.JComboBox<String> cbxRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tabla;
    private javax.swing.JTextField txtfContenido;
    // End of variables declaration//GEN-END:variables
}
