/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPersona;
import Controlador.ControladorMarca;
import Controlador.ControladorProducto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES
 */
public class VentanaMarca extends javax.swing.JFrame {
    ControladorMarca mc = new ControladorMarca();
    ControladorPersona cp;
    ControladorProducto pc;
    /**
     * Creates new form VentanaMarca
     */
    public VentanaMarca() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * Constructor de la ventana marca
     * @param pc Controlador de producto
     * @param cp Controlador de persona
     */
     public VentanaMarca(ControladorProducto pc, ControladorPersona cp) {
        initComponents();
        this.pc = pc;
        this.cp = cp;
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Limpia los TextField de la ventana
     */
    private void limpiar(){
        txtfNombreMarca.setText("");
        txtfPaisMarca.setText("");
        mc.setMarca(null);
    }
    
    /**
     * Guarda la marca en un archivo
     */
    private void guardar(){
        if(!txtfNombreMarca.getText().trim().isEmpty() && !txtfPaisMarca.getText().trim().isEmpty()){
            mc.getMarca().setNombreMarca(txtfNombreMarca.getText());
            mc.getMarca().setPaisOrigen(txtfPaisMarca.getText());
            if(mc.guardar()){
                limpiar();
                JOptionPane.showMessageDialog(null, "Marca Registrada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfNombreMarca = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtfPaisMarca = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        butGuardar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        butVolver = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoMarca.png"))); // NOI18N
        jLabel3.setText("   REGISTRO DE MARCA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 590, -1));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pais de origen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtfNombreMarca.setBackground(new java.awt.Color(51, 153, 255));
        txtfNombreMarca.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfNombreMarca.setForeground(new java.awt.Color(0, 0, 0));
        txtfNombreMarca.setBorder(null);
        jPanel1.add(txtfNombreMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, 1));

        txtfPaisMarca.setBackground(new java.awt.Color(51, 153, 255));
        txtfPaisMarca.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfPaisMarca.setForeground(new java.awt.Color(0, 0, 0));
        txtfPaisMarca.setBorder(null);
        jPanel1.add(txtfPaisMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 140, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 140, 1));

        butGuardar.setBackground(new java.awt.Color(51, 153, 255));
        butGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butGuardarMouseExited(evt);
            }
        });
        butGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoGuardar.png"))); // NOI18N
        butGuardar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GUARDAR");
        butGuardar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -2, 240, 50));

        jPanel1.add(butGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 285, 50));

        butVolver.setBackground(new java.awt.Color(51, 153, 255));
        butVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butVolverMouseExited(evt);
            }
        });
        butVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRegresar.png"))); // NOI18N
        butVolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGRESAR");
        butVolver.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -2, 230, 50));

        jPanel1.add(butVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 285, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butGuardarMouseClicked
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_butGuardarMouseClicked

    private void butGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butGuardarMouseEntered
        // TODO add your handling code here:
        Color color1 = new Color(0, 153, 204);
        butGuardar.setBackground(color1);
    }//GEN-LAST:event_butGuardarMouseEntered

    private void butGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butGuardarMouseExited
        // TODO add your handling code here:
        Color color1 = new Color(51,153,255);
        butGuardar.setBackground(color1);
    }//GEN-LAST:event_butGuardarMouseExited

    private void butVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_butVolverMouseClicked

    private void butVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butVolverMouseEntered
        // TODO add your handling code here:
         Color color1 = new Color(0, 153, 204);
        butVolver.setBackground(color1);
    }//GEN-LAST:event_butVolverMouseEntered

    private void butVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butVolverMouseExited
        // TODO add your handling code here:
        Color color1 = new Color(51,153,255);
        butVolver.setBackground(color1);
    }//GEN-LAST:event_butVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel butGuardar;
    private javax.swing.JPanel butVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtfNombreMarca;
    private javax.swing.JTextField txtfPaisMarca;
    // End of variables declaration//GEN-END:variables
}
