/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFacturaCompra;
import Controlador.ControladorKardex;
import Controlador.ControladorProducto;
import java.awt.Dimension;

/**
 *
 * @author jere_
 */
public class VentanaAgregarCompra extends javax.swing.JFrame {

    private ControladorFacturaCompra ctrlFacturaCompra;//ControladorFacturaCompra usado para llamar a los metodos de este
    private ControladorProducto ctrlProducto;//ControladorProducto usado para llamar a los metodos de este
    private ControladorKardex ck = new ControladorKardex();//ControladorKardex usado para llamar a los metodos de este

    /**
     * Constructor de la ventana, que sirve para pasar informacion del cliente que inicio sesion y la lista de productos
     * @param ctrlFacturaCompra el controladorFacturaCompra que contiene la nueva facturaCompra de la compra que se va a realizar
     * @param ctrlProducto el controladorProducto que contiene la lista de Productos
     */
    public VentanaAgregarCompra(ControladorFacturaCompra ctrlFacturaCompra, ControladorProducto ctrlProducto) {
        initComponents();
        this.setSize(new Dimension(290, 311));
        this.setLocationRelativeTo(null);
        this.ctrlFacturaCompra = ctrlFacturaCompra;
        this.ctrlProducto = ctrlProducto;
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfCantidad = new javax.swing.JTextField();
        txtfPrecioUnitario = new javax.swing.JTextField();
        btAgregarCompra = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        cbxProductos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio Unitario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtfCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtfCantidad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfCantidad.setBorder(null);
        jPanel1.add(txtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 110, 20));

        txtfPrecioUnitario.setBackground(new java.awt.Color(255, 255, 255));
        txtfPrecioUnitario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfPrecioUnitario.setBorder(null);
        jPanel1.add(txtfPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, 20));

        btAgregarCompra.setBackground(new java.awt.Color(51, 153, 255));
        btAgregarCompra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btAgregarCompra.setForeground(new java.awt.Color(0, 0, 0));
        btAgregarCompra.setText("Agregar");
        btAgregarCompra.setBorderPainted(false);
        btAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btAgregarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, 30));

        btCancelar.setBackground(new java.awt.Color(51, 153, 255));
        btCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.setBorderPainted(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 30));

        cbxProductos.setBackground(new java.awt.Color(255, 255, 255));
        cbxProductos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbxProductos.setBorder(null);
        jPanel1.add(cbxProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 110, 10));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 320, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 290, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para agregar una compra a la facturaCompra del proveedor
     * @param evt Evento de tipo ActionEvent
     */
    private void btAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCompraActionPerformed
        String producto = cbxProductos.getSelectedItem().toString();
        String precioUnitario = txtfPrecioUnitario.getText();
        String cantidad = txtfCantidad.getText();

        Integer index = cbxProductos.getSelectedIndex();

        if (cantidad.isBlank() || precioUnitario.isBlank() || producto.isBlank()) {
            System.out.println("Debe llenar todos los datos");
        } else {
            ctrlFacturaCompra.agregarDetalleCompra(ctrlProducto.getProductos().getByIndex(index).getId(), Integer.valueOf(cantidad), Double.valueOf(precioUnitario));
            ctrlProducto.getProductos().getByIndex(index).setStock(ctrlProducto.getProductos().getByIndex(index).getStock() + Integer.valueOf(cantidad));
            ctrlProducto.getProductos().getByIndex(index).setPrecioCompra(Double.valueOf(precioUnitario));
            ck.setListaKardex(ck.listar());
            ck.setKardex(ck.getListaKardex().getByIndex(index));
            if (ck.getKardex().getCantidad() == 0) {
                ck.getKardex().setCantidad(Integer.valueOf(cantidad));
                ck.getKardex().setCantidadTotal(Integer.valueOf(cantidad));
                ck.getKardex().setTotal(Double.valueOf(precioUnitario) * Integer.valueOf(cantidad));
                ck.getKardex().setTotalFinal(Double.valueOf(precioUnitario) * Integer.valueOf(cantidad));
                ck.getKardex().setValorUnitario(Double.valueOf(precioUnitario));
                ck.modificar(ck.getKardex(), index);
            } else{
                ck.setKardex(null);
                ck.getKardex().setCantidad(Integer.valueOf(cantidad));
                ck.getKardex().setCantidadTotal(ctrlProducto.getProductos().getByIndex(index).getStock());
                ck.getKardex().setDetalle(ctrlProducto.getProductos().getByIndex(index).getNombre());
                ck.getKardex().setFecha(ctrlProducto.getProductos().getByIndex(index).getFechaCompra());
                ck.getKardex().setPrenda(ctrlProducto.getProductos().getByIndex(index).getPrenda());
                ck.getKardex().setTipoId(Long.valueOf("0"));
                ck.getKardex().setTotal(Double.valueOf(precioUnitario) * Integer.valueOf(cantidad));
                ck.getKardex().setTotalFinal(Double.valueOf(precioUnitario) * Integer.valueOf(cantidad));
                ck.getKardex().setValorUnitario(Double.valueOf(precioUnitario));
                ck.guardar();
            }
            
            ctrlProducto.modificar(ctrlProducto.getProductos().getByIndex(index), index);
            this.dispose();
        }
    }//GEN-LAST:event_btAgregarCompraActionPerformed

    /**
     * Evento para cancelar la adicion de una nueva compra y cerrar la ventana
     * @param evt 
     */
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarCompra(new ControladorFacturaCompra(0.12), new ControladorProducto()).setVisible(true);
            }
        });
    }

    /**
     * Evento para cargar los comboBox de la ventana
     */
    private void cargarComboBox() {
        for (int i = 0; i < ctrlProducto.getProductos().length(); i++) {
            cbxProductos.addItem(ctrlProducto.getProductos().getByIndex(i).getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCompra;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtfCantidad;
    private javax.swing.JTextField txtfPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
