/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFactura;
import Controlador.ControladorKardex;
import Controlador.ControladorPersona;
import Controlador.ControladorValoresPorDefecto;
import Controlador.EstructurasDinamicas.Lista;
import Controlador.ControladorProducto;
import Modelo.Enum.Color;
import Modelo.Enum.Prenda;
import Modelo.Enum.TipoPrenda;
import Modelo.Producto;
import Vista.ModeloTablas.ModeloTablaProductoCompra;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jere_
 */
public class VentanaComprar extends javax.swing.JFrame {

    private ControladorProducto ctrlProducto;
    ModeloTablaProductoCompra modelo = new ModeloTablaProductoCompra();
    private ControladorPersona ctrlPersona;
    private ControladorFactura ctrlFactura;
    private ControladorValoresPorDefecto ctrlVPD;
    private ControladorKardex ck = new ControladorKardex();

    /**
     * 
     * @param ctrlPersona
     * @param ck1 
     */
    public VentanaComprar(ControladorPersona ctrlPersona) {
        initComponents();
        this.setLocationRelativeTo(null);
        ck.setListaKardex(ck.listar());
        ctrlProducto = new ControladorProducto();
        ctrlProducto.setProductos(ctrlProducto.listar());
        this.ctrlPersona = ctrlPersona;
        this.ctrlVPD = new ControladorValoresPorDefecto();
        ctrlFactura = new ControladorFactura(ctrlVPD.getVpd().getIVA());
        ctrlFactura.setPersona(ctrlPersona.getPersona());

        cbxCriterioBusqueda.removeAllItems();
        cargarTabla();
        cargarCombo();
        ocultarColumnaID(jtCarrito);
        ocultarColumnaID(jtListaProductos);

        DefaultTableModel modelo = (DefaultTableModel) jtCarrito.getModel();
        modelo.setRowCount(0);
        jtCarrito.setModel(modelo);

        ctrlFactura.getFactura();
        ctrlFactura.getFactura().setId(Integer.toUnsignedLong(ctrlPersona.getPersona().getFacturas().length() + 1));
        ctrlFactura.getFactura().setFecha(ctrlPersona.convertToDateViaInstant(LocalDate.now()));
        ctrlFactura.generar_nroFactura();

        jmComprar.setEnabled(false);
        comprobarRol();
    }

    private void cargarCombo() {
        cbxCriterioBusqueda.addItem("Marca");
        cbxCriterioBusqueda.addItem("Nombre");
        cbxCriterioBusqueda.addItem("Tipo Prenda");
        cbxCriterioBusqueda.addItem("Prenda");
        cbxCriterioBusqueda.addItem("Color");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtfBuscar = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCriterioBusqueda = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btAgregarCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblProductoSelect = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarrito = new javax.swing.JTable();
        btFacturar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        txtfCantidad = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmComprar = new javax.swing.JMenu();
        jmPerfil = new javax.swing.JMenu();
        jmFacturarCompra = new javax.swing.JMenu();
        jmAgregarProducto = new javax.swing.JMenu();
        jmKardex = new javax.swing.JMenu();
        jmRegistros = new javax.swing.JMenu();
        jmSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Nombre", "TipoPrenda", "Color", "Tipo", "Talla", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaProductos);

        jLabel1.setText("IMAG");

        txtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBuscarActionPerformed(evt);
            }
        });
        txtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfBuscarKeyReleased(evt);
            }
        });

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("IMAGEN");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comprar");

        jLabel4.setText("Buscar por:");

        btAgregarCarrito.setText("Añadir al carrito");
        btAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCarritoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad");

        jLabel5.setText("Producto Seleccionado: ");

        jtCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Cantidad", "Precio", "PrecioTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCarrito.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarritoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCarrito);
        if (jtCarrito.getColumnModel().getColumnCount() > 0) {
            jtCarrito.getColumnModel().getColumn(0).setResizable(false);
            jtCarrito.getColumnModel().getColumn(1).setResizable(false);
            jtCarrito.getColumnModel().getColumn(2).setResizable(false);
            jtCarrito.getColumnModel().getColumn(3).setResizable(false);
            jtCarrito.getColumnModel().getColumn(4).setResizable(false);
        }

        btFacturar.setText("Facturar");
        btFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxCriterioBusqueda, 0, 112, Short.MAX_VALUE)
                            .addComponent(txtfBuscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAgregarCarrito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(lblProductoSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblProductoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btAgregarCarrito))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btRemover)
                                .addGap(18, 18, 18)
                                .addComponent(btFacturar)
                                .addGap(15, 15, 15)))))
                .addGap(39, 39, 39))
        );

        jmComprar.setText("Comprar");
        jmComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmComprarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmComprar);

        jmPerfil.setText("Perfil");
        jmPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPerfilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmPerfil);

        jmFacturarCompra.setText("Abastecer");
        jmFacturarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmFacturarCompraMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmFacturarCompra);

        jmAgregarProducto.setText("Productos");
        jmAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAgregarProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAgregarProducto);

        jmKardex.setText("Kardex");
        jmKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmKardexMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmKardex);

        jmRegistros.setText("Registros");
        jmRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRegistrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmRegistros);

        jmSistema.setText("Sistema");
        jmSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSistemaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar() {
        switch (cbxCriterioBusqueda.getSelectedIndex()) {
            case 0:
                ctrlProducto.setProducto(new Producto());
                ctrlProducto.getProducto().getMarca().setNombreMarca(txtfBuscar.getText().toLowerCase());
                modelo.setLista(ctrlProducto.getProductos().multipleSearch("marca", ctrlProducto.getProducto().getMarca()));
                break;
            case 1:
                modelo.setLista(ctrlProducto.getProductos().multipleSearch("nombre", txtfBuscar.getText().toLowerCase()));
                break;
            case 2:

                for (TipoPrenda t : TipoPrenda.values()) {
                    if (t.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("tipoPrenda", TipoPrenda.valueOf(t.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
            case 3:
                for (Prenda p : Prenda.values()) {
                    if (p.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("prenda", Prenda.valueOf(p.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
            case 4:
                for (Color c : Color.values()) {
                    if (c.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("color", Color.valueOf(c.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
        }
    }
    private void txtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBuscarActionPerformed

    }//GEN-LAST:event_txtfBuscarActionPerformed

    private void jtListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaProductosMouseClicked
        try 
        {
            generarImagen(jtListaProductos);
            Integer index = jtListaProductos.getSelectedRow();
            Integer id = ((Long) jtListaProductos.getValueAt(index, 0)).intValue();
            ctrlProducto.setProducto(ctrlProducto.getProductos().getByIndex(id - 1));
            lblProductoSelect.setText(ctrlProducto.getProducto().getNombre());
            jtCarrito.clearSelection();
        } 
        catch (Exception e) 
        {
        }
    }//GEN-LAST:event_jtListaProductosMouseClicked

    private void txtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBuscarKeyReleased

        jtListaProductos.clearSelection();

        if (txtfBuscar.getText().isBlank()) {
            cargarTabla();
        } else {
            buscar();
            jtListaProductos.setModel(modelo);
            jtListaProductos.updateUI();
        }
    }//GEN-LAST:event_txtfBuscarKeyReleased

    private void jtCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarritoMouseClicked
        jtListaProductos.clearSelection();
        generarImagen(jtCarrito);
    }//GEN-LAST:event_jtCarritoMouseClicked

    private void btAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCarritoActionPerformed
    
        try 
        {
            if (jtListaProductos.getSelectedRow() == -1)
            {
                System.out.println("Debe seleccionar un producto");
            } 
            else 
            {
                DefaultTableModel modelo = (DefaultTableModel) jtCarrito.getModel();

                Object[] fila = new Object[5];

                fila[0] = ctrlProducto.getProducto().getId();
                fila[1] = ctrlProducto.getProducto().getNombre();
                fila[2] = txtfCantidad.getText();
                fila[3] = ctrlProducto.getProducto().getPrecioVenta();
                fila[4] = (ctrlProducto.getProducto().getPrecioVenta() * Integer.valueOf(txtfCantidad.getText()));
                modelo.addRow(fila);
                jtCarrito.setModel(modelo);
            }
            registrarDetalle();
        }
        catch (ClassCastException e) {
        }
        
    }//GEN-LAST:event_btAgregarCarritoActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed

        Integer index = jtCarrito.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Debe escoger un producto del carrito", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ctrlFactura.borrarDetalle((Long) jtCarrito.getValueAt(index, 0));
            DefaultTableModel modelotmp = (DefaultTableModel) jtCarrito.getModel();
            modelotmp.removeRow(index);
        }
        jtCarrito.clearSelection();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void jmComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmComprarMouseClicked

    }//GEN-LAST:event_jmComprarMouseClicked

    private void jmFacturarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmFacturarCompraMouseClicked

        VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, ctrlProducto);
        vtFacturarCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmFacturarCompraMouseClicked

    private void btFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturarActionPerformed

        ctrlFactura.calcularSubTotal();
        ctrlFactura.calcularIva();
        ctrlFactura.calcularTotal();
        VentanaFactura vtFactura = new VentanaFactura(null, true, ctrlPersona, ctrlFactura, ctrlProducto);
        vtFactura.setVisible(true);
        vtFactura.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        vtFactura.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("hola");
                cerrarVentanasSecundarias();
                cargarTabla();
            }
        });
    }//GEN-LAST:event_btFacturarActionPerformed

    private void jmRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRegistrosMouseClicked
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, ctrlProducto);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmRegistrosMouseClicked

    private void jmPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPerfilMouseClicked
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, ctrlProducto);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmPerfilMouseClicked

    private void jmSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSistemaMouseClicked
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, ctrlProducto);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmSistemaMouseClicked

    private void jmAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAgregarProductoMouseClicked
        VentanaProducto vp = new VentanaProducto(this.ctrlProducto, this.ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_jmAgregarProductoMouseClicked

    private void jmKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmKardexMouseClicked
        // TODO add your handling code here:
        VentanaKardex vk = new VentanaKardex(ctrlProducto, ctrlPersona);
        this.dispose();
        vk.setVisible(true);
    }//GEN-LAST:event_jmKardexMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaComprar(new ControladorPersona()).setVisible(true);
            }
        });
    }

    private void generarImagen(JTable jt) {
        Integer index = jt.getSelectedRow();
        Integer id = ((Long) jt.getValueAt(index, 0)).intValue();
        ImageIcon icon = ctrlProducto.getProductos().getByIndex(id - 1).getIcon();
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setText(null);
        lblFoto.setIcon(icono);
    }

    private void cargarTabla() {
        modelo.setLista(ctrlProducto.getProductos());
        jtListaProductos.setModel(modelo);
        jtListaProductos.updateUI();
    }

    private void ocultarColumnaID(JTable jt) {
        jt.getColumnModel().getColumn(0).setMaxWidth(0);
        jt.getColumnModel().getColumn(0).setMinWidth(0);
        jt.getColumnModel().getColumn(0).setPreferredWidth(0);
        jt.getColumnModel().getColumn(0).setResizable(false);
    }

    private void registrarDetalle() {
        Integer cantidad = Integer.valueOf(txtfCantidad.getText().trim());
        ctrlFactura.cargarDetalleFactura(ctrlProducto.getProducto().getId(), ctrlProducto.getProducto(), cantidad, ctrlProducto.getProducto().getPrecioVenta(), (ctrlProducto.getProducto().getPrecioVenta()) * cantidad);
        ctrlFactura.guardarDetalleFactura();
    }

    private void cerrarVentanasSecundarias() {
        this.setEnabled(true);
        this.toFront();
    }

    private void comprobarRol() {
        System.out.println("ComprobarRol: " + ctrlPersona.getPersona().getId_Rol().getNombreRol());
        if (ctrlPersona.getPersona().getId_Rol().getNombreRol().equals("cliente")) {
            jmFacturarCompra.setEnabled(false);
            jmFacturarCompra.setVisible(false);
            jmKardex.setEnabled(false);
            jmKardex.setVisible(false);
            jmRegistros.setEnabled(false);
            jmRegistros.setVisible(false);
            jmAgregarProducto.setEnabled(false);
            jmAgregarProducto.setVisible(false);
            jmSistema.setEnabled(false);
            jmSistema.setVisible(false);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCarrito;
    private javax.swing.JButton btFacturar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox<String> cbxCriterioBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jmAgregarProducto;
    private javax.swing.JMenu jmComprar;
    private javax.swing.JMenu jmFacturarCompra;
    private javax.swing.JMenu jmKardex;
    private javax.swing.JMenu jmPerfil;
    private javax.swing.JMenu jmRegistros;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JTable jtCarrito;
    private javax.swing.JTable jtListaProductos;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblProductoSelect;
    private javax.swing.JTextField txtfBuscar;
    private javax.swing.JTextField txtfCantidad;
    // End of variables declaration//GEN-END:variables
}
