/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFacturaCompra;
import Controlador.ControladorPersona;
import Controlador.ControladorProducto;
import Controlador.ControladorProveedor;
import Controlador.ControladorValoresPorDefecto;
import com.itextpdf.text.DocumentException;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jere_
 */
public class VentanaFacturarCompras extends javax.swing.JFrame {

    private ControladorProveedor ctrlProveedor;
    private ControladorFacturaCompra ctrlFacturaCompra;
    private ControladorPersona ctrlPersona;
    private ControladorValoresPorDefecto ctrlVPD;
    private ControladorProducto cp;
    
    /**
     * Creates new form VentanaAgregarCompra
     */
    public VentanaFacturarCompras(ControladorPersona ctrlPersona, ControladorProducto ctrlProducto) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ctrlVPD = new ControladorValoresPorDefecto();
        
        ctrlProveedor = new ControladorProveedor();
        ctrlFacturaCompra = new ControladorFacturaCompra(ctrlVPD.getVpd().getIVA());
        this.ctrlPersona = ctrlPersona;
        this.cp = ctrlProducto;
        ctrlProveedor.setListaProveedores(ctrlProveedor.listar());
        ctrlProducto.setProductos(ctrlProducto.listar());
        cargarCBXProveedor();
        instanciarDatosFactura();
        
        jmFacturarCompra.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalleFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIvaIndicador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btFacturar = new javax.swing.JButton();
        btAgregarCompra = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        btAgregarProveedor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblNroFactura = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jmFacturarCompra = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(jtDetalleFactura);
        if (jtDetalleFactura.getColumnModel().getColumnCount() > 0) {
            jtDetalleFactura.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jLabel1.setText("NroFactura:");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Subtotal");

        lblIvaIndicador.setText("IVA(12%)");

        jLabel5.setText("Total");

        lblSubtotal.setText("0.00 $");

        lblIVA.setText("0.00 $");

        lblTotal.setText("0.00 $");

        btFacturar.setText("Facturar");
        btFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturarActionPerformed(evt);
            }
        });

        btAgregarCompra.setText("Agregar Compra");
        btAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCompraActionPerformed(evt);
            }
        });

        jLabel9.setText("Proveedor");

        cbxProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProveedorItemStateChanged(evt);
            }
        });

        btAgregarProveedor.setText("Agregar Proveedor");
        btAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProveedorActionPerformed(evt);
            }
        });

        jLabel10.setText("Dirección");

        lblDireccion.setText("........");

        jLabel12.setText("R.U.C");

        lblRUC.setText("........");

        lblNroFactura.setText("........");

        lblFecha.setText("........");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Factura Compra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(lblFecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNroFactura)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(25, 25, 25)
                                .addComponent(lblDireccion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRUC)))
                        .addGap(243, 243, 243))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAgregarProveedor)
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btFacturar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btAgregarCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(lblIvaIndicador))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubtotal)
                                    .addComponent(lblIVA)
                                    .addComponent(lblTotal))))
                        .addGap(101, 101, 101))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblNroFactura))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAgregarProveedor)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblFecha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblDireccion))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblRUC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarCompra)
                    .addComponent(jLabel3)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIvaIndicador)
                    .addComponent(lblIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(btFacturar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jMenu5.setText("Comprar");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Perfil");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jmFacturarCompra.setText("Abastecer");
        jmFacturarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmFacturarCompraMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmFacturarCompra);

        jMenu2.setText("Productos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Kardex");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Registros");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu8.setText("Sistema");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturarActionPerformed
    
        if(JOptionPane.showConfirmDialog(null, "Desea guardar la factura")== 0)
        {
            try {
                String CARPETA = "";
                JFileChooser chooser = new JFileChooser();
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                Component parent = null;
                int returnVal = chooser.showSaveDialog(parent);
                
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    String selectPath = chooser.getSelectedFile().getPath();
                    CARPETA = selectPath + File.separatorChar;
                    CARPETA += ctrlFacturaCompra.getFactura().getNroFactura() + ".pdf";
                }
                ctrlProveedor.guardarFacturaCompra(ctrlFacturaCompra.getFactura());
                ctrlProveedor.crearPDF(ctrlFacturaCompra.getFactura(), CARPETA, cbxProveedor.getSelectedIndex());
            } catch (DocumentException ex) {
                Logger.getLogger(VentanaFacturarCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else
        {
            ctrlProveedor.guardarFacturaCompra(ctrlFacturaCompra.getFactura());
        }
        
    }//GEN-LAST:event_btFacturarActionPerformed

    private void btAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProveedorActionPerformed
        VentanaAgregarProveedor vtAgrProveedor = new VentanaAgregarProveedor(ctrlProveedor);
        vtAgrProveedor.setVisible(true);
        this.setEnabled(false);
        vtAgrProveedor.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowDeactivated(WindowEvent e) {
                
                cerrarVentanasSecundarias();
                cargarCBXProveedor();
            }
        });      
    }//GEN-LAST:event_btAgregarProveedorActionPerformed

    private void btAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCompraActionPerformed
        VentanaAgregarCompra vtAgrCompra = new VentanaAgregarCompra(ctrlFacturaCompra, cp);
        vtAgrCompra.setVisible(true);
        vtAgrCompra.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        vtAgrCompra.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowDeactivated(WindowEvent e) {
                cerrarVentanasSecundarias();
                if(ctrlFacturaCompra.getFactura().getListaDetalles().length() != 0)
                {
                    agregarCompraTabla();
                }
            }
        });
    }//GEN-LAST:event_btAgregarCompraActionPerformed

    private void cbxProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProveedorItemStateChanged
        
        Integer indice = cbxProveedor.getSelectedIndex();
        if(indice == -1) 
        {
            System.out.println("hola");
        }
        else 
        {
            lblRUC.setText(ctrlProveedor.getListaProveedores().getByIndex(cbxProveedor.getSelectedIndex()).getRuc());
            lblDireccion.setText(ctrlProveedor.getListaProveedores().getByIndex(cbxProveedor.getSelectedIndex()).getDireccionProveedor());
            ctrlProveedor.setProveedor(ctrlProveedor.getListaProveedores().getByIndex(indice));
        }
    }//GEN-LAST:event_cbxProveedorItemStateChanged

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        VentanaComprar vc = new VentanaComprar(ctrlPersona);
        this.dispose();
        vc.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, cp);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jmFacturarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmFacturarCompraMouseClicked
        // TODO add your handling code here:
        VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, cp);
        vtFacturarCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmFacturarCompraMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        VentanaProducto vp = new VentanaProducto(cp, ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        VentanaKardex ventana = new VentanaKardex(this.cp, this.ctrlPersona);
        this.dispose();
        ventana.show();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, cp);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, cp);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFacturarCompras(new ControladorPersona(), new ControladorProducto()).setVisible(true);
            }
        });
    }
    
    private void cerrarVentanasSecundarias()
    {
        this.setEnabled(true);
        this.toFront();
    }
    
    private void cargarCBXProveedor()
    {
        cbxProveedor.removeAllItems();
        
        for (int i = 0; i < ctrlProveedor.getListaProveedores().length(); i++)
        {
            cbxProveedor.addItem(ctrlProveedor.getListaProveedores().getByIndex(i).getNombreProveedor() + " "  + ctrlProveedor.getListaProveedores().getByIndex(i).getApellidoProveedor());
        }
    }
    
    private void instanciarDatosFactura()
    {
        ctrlFacturaCompra.generarNumeroFactura();
        ctrlFacturaCompra.calcularFecha();
        
        DateFormat dfD = DateFormat.getDateInstance(DateFormat.SHORT);
        DateFormat dfH = DateFormat.getTimeInstance(DateFormat.MEDIUM);
        
        lblNroFactura.setText(ctrlFacturaCompra.getFactura().getNroFactura());
        lblFecha.setText(dfD.format(ctrlFacturaCompra.getFactura().getFecha()) + " " + dfH.format(ctrlFacturaCompra.getFactura().getFecha()));
    }
    
    private void agregarCompraTabla()
    {
        DefaultTableModel modelo=(DefaultTableModel) jtDetalleFactura.getModel();
        modelo.setRowCount(0);
        jtDetalleFactura.setModel(modelo);
        
        Object[] fila = new Object[4];
        
        for (int i = 0; i < ctrlFacturaCompra.getFactura().getListaDetalles().length(); i++)
        {
            fila[0] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getIdProducto();
            fila[1] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getCantidad();
            fila[2] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getPrecioUnitario();
            fila[3] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getPrecioTotal();
            modelo.addRow(fila);
        }
        
        jtDetalleFactura.setModel(modelo);
        calcularCostos();
    }
    
    private void calcularCostos()
    {
        DecimalFormat dc = new DecimalFormat("##.##");
        
        ctrlFacturaCompra.setIva(0.12);
        lblSubtotal.setText(Double.toString(ctrlFacturaCompra.getFactura().getSubTotal()));
        lblIVA.setText(dc.format(ctrlFacturaCompra.getFactura().getIva()));
        lblTotal.setText(ctrlFacturaCompra.getFactura().getTotal().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCompra;
    private javax.swing.JButton btAgregarProveedor;
    private javax.swing.JButton btFacturar;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmFacturarCompra;
    private javax.swing.JTable jtDetalleFactura;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIvaIndicador;
    private javax.swing.JLabel lblNroFactura;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
