/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFacturaCompra;
import Controlador.ControladorPersona;
import Controlador.ControladorProducto;
import Controlador.ControladorProveedor;
import Controlador.ControladorValoresPorDefecto;
import com.itextpdf.text.DocumentException;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jere_
 */
public class VentanaFacturarCompras extends javax.swing.JFrame {

    private ControladorProveedor ctrlProveedor;//ControladorProveedor usado para llamar a los metodos de este
    private ControladorFacturaCompra ctrlFacturaCompra;//ControladorFacturaCompra usado para llamar a los metodos de este
    private ControladorPersona ctrlPersona;//ControladorPersona usado para llamar a los metodos de este
    private ControladorValoresPorDefecto ctrlVPD;//ControladorValoresPorDefecto usado para llamar a los metodos de este
    private ControladorProducto cp;////ControladorProducto usado para llamar a los metodos de este
    
    /**
     * Constructor de la ventana, que sirve para pasar la informacion del persona que inicio sesion y de los productos del sistema
     * @param ctrlPersona el controladorPersona que contiene a la persona que inicio sesion
     * @param ctrlProducto el ControladorProducto que contiene a todos los productos almacenados en el sistema
     */
    public VentanaFacturarCompras(ControladorPersona ctrlPersona, ControladorProducto ctrlProducto) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ctrlVPD = new ControladorValoresPorDefecto();
        
        ctrlProveedor = new ControladorProveedor();
        ctrlFacturaCompra = new ControladorFacturaCompra(ctrlVPD.getVpd().getIVA());
        this.ctrlPersona = ctrlPersona;
        this.cp = ctrlProducto;
        ctrlProveedor.setListaProveedores(ctrlProveedor.listar());
        ctrlProducto.setProductos(ctrlProducto.listar());
        cargarCBXProveedor();
        instanciarDatosFactura();
        
        jmFacturarCompra.setEnabled(false);
        btAgregarCompra.setFocusPainted(false);
        btFacturar.setFocusPainted(false);
        btAgregarProveedor.setFocusPainted(false);
        btAgregarCompra.setFocusable(false);
        btFacturar.setFocusable(false);
        btAgregarProveedor.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIvaIndicador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblNroFactura = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalleFactura = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btFacturar = new javax.swing.JButton();
        btAgregarCompra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btAgregarProveedor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jmFacturarCompra = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NroFactura:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 90, 74, 16);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 130, 42, 16);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Subtotal");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 350, 53, 20);

        lblIvaIndicador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIvaIndicador.setForeground(new java.awt.Color(0, 0, 0));
        lblIvaIndicador.setText("IVA(12%)");
        jPanel1.add(lblIvaIndicador);
        lblIvaIndicador.setBounds(490, 380, 60, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(510, 410, 31, 20);

        lblSubtotal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotal.setText("0.00 $");
        jPanel1.add(lblSubtotal);
        lblSubtotal.setBounds(560, 350, 40, 20);

        lblIVA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblIVA.setText("0.00 $");
        jPanel1.add(lblIVA);
        lblIVA.setBounds(560, 380, 40, 20);

        lblTotal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("0.00 $");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(560, 410, 40, 20);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Proveedor:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 90, 70, 16);

        cbxProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cbxProveedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbxProveedor.setBorder(null);
        cbxProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProveedorItemStateChanged(evt);
            }
        });
        cbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(cbxProveedor);
        cbxProveedor.setBounds(430, 90, 130, 20);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Dirección:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 130, 61, 16);

        lblDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblDireccion);
        lblDireccion.setBounds(430, 130, 110, 20);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("R.U.C:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 170, 39, 16);

        lblRUC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblRUC.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblRUC);
        lblRUC.setBounds(430, 170, 110, 20);

        lblNroFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNroFactura.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblNroFactura);
        lblNroFactura.setBounds(160, 90, 110, 20);

        lblFecha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblFecha);
        lblFecha.setBounds(160, 130, 140, 20);

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(430, 190, 110, 10);

        jSeparator3.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(160, 110, 110, 10);

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(160, 150, 140, 10);

        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(430, 150, 110, 10);

        jtDetalleFactura.setBackground(new java.awt.Color(255, 255, 255));
        jtDetalleFactura.setForeground(new java.awt.Color(0, 0, 0));
        jtDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ));
        jtDetalleFactura.setGridColor(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jtDetalleFactura);
        if (jtDetalleFactura.getColumnModel().getColumnCount() > 0) {
            jtDetalleFactura.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 210, 548, 129);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setBackground(new java.awt.Color(51, 153, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Factura Compra");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dineroIcono.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(143, 143, 143))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-10, 20, 670, 50);

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(-10, 480, 670, 60);

        btFacturar.setBackground(new java.awt.Color(255, 255, 255));
        btFacturar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facturarIcono.png"))); // NOI18N
        btFacturar.setBorder(null);
        btFacturar.setContentAreaFilled(false);
        btFacturar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btFacturar.setFocusPainted(false);
        btFacturar.setFocusable(false);
        btFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturarActionPerformed(evt);
            }
        });
        jPanel1.add(btFacturar);
        btFacturar.setBounds(150, 350, 50, 60);

        btAgregarCompra.setBackground(new java.awt.Color(255, 255, 255));
        btAgregarCompra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btAgregarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btAgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoAgregarCarrito.png"))); // NOI18N
        btAgregarCompra.setBorder(null);
        btAgregarCompra.setContentAreaFilled(false);
        btAgregarCompra.setFocusPainted(false);
        btAgregarCompra.setFocusable(false);
        btAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btAgregarCompra);
        btAgregarCompra.setBounds(60, 360, 60, 44);

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(-10, 250, 680, 60);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Agregar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 410, 60, 16);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Facturar");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 410, 60, 16);

        btAgregarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btAgregarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarIcono_1.png"))); // NOI18N
        btAgregarProveedor.setBorder(null);
        btAgregarProveedor.setBorderPainted(false);
        btAgregarProveedor.setContentAreaFilled(false);
        btAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btAgregarProveedor);
        btAgregarProveedor.setBounds(570, 80, 30, 30);

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenu5.setText("Comprar");
        jMenu5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Perfil");
        jMenu6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jmFacturarCompra.setText("Abastecer");
        jmFacturarCompra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmFacturarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmFacturarCompraMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmFacturarCompra);

        jMenu2.setText("Productos");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Kardex");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Registros");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu8.setBackground(new java.awt.Color(0, 0, 0));
        jMenu8.setBorder(null);
        jMenu8.setForeground(new java.awt.Color(0, 0, 0));
        jMenu8.setText("Sistema");
        jMenu8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para facturar las compras que se le realizo al proveedor
     * @param evt evento de tipo actionEvent
     */
    private void btFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturarActionPerformed
    
        Integer decision = JOptionPane.showConfirmDialog(null, "Desea guardar la factura");
        if(decision== 0)
        {
            try {
                String CARPETA = "";
                JFileChooser chooser = new JFileChooser();
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                Component parent = null;
                int returnVal = chooser.showSaveDialog(parent);
                
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    String selectPath = chooser.getSelectedFile().getPath();
                    CARPETA = selectPath + File.separatorChar;
                    CARPETA += ctrlFacturaCompra.getFactura().getNroFactura() + ".pdf";
                }
                ctrlProveedor.guardarFacturaCompra(ctrlFacturaCompra.getFactura());
                ctrlProveedor.crearPDF(ctrlFacturaCompra.getFactura(), CARPETA, cbxProveedor.getSelectedIndex());
            } catch (DocumentException ex) {
                Logger.getLogger(VentanaFacturarCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else if(decision != 2)
        {
            ctrlProveedor.guardarFacturaCompra(ctrlFacturaCompra.getFactura());
        }
        
    }//GEN-LAST:event_btFacturarActionPerformed

    /**
     * Metodo para cargar la ventana de AgregarCompra 
     * @param evt 
     */
    private void btAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCompraActionPerformed
        VentanaAgregarCompra vtAgrCompra = new VentanaAgregarCompra(ctrlFacturaCompra, cp);
        vtAgrCompra.setVisible(true);
        vtAgrCompra.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        vtAgrCompra.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowDeactivated(WindowEvent e) {
                cerrarVentanasSecundarias();
                if(ctrlFacturaCompra.getFactura().getListaDetalles().length() != 0)
                {
                    agregarCompraTabla();
                }
            }
        });
    }//GEN-LAST:event_btAgregarCompraActionPerformed

    /**
     * Evento para cargar la informacion del proveedor seleccionado
     * @param evt  evento de tipo itemEvent
     */
    private void cbxProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProveedorItemStateChanged
        
        Integer indice = cbxProveedor.getSelectedIndex();
        if(indice == -1) 
        {
            System.out.println("hola");
        }
        else 
        {
            lblRUC.setText(ctrlProveedor.getListaProveedores().getByIndex(cbxProveedor.getSelectedIndex()).getRuc());
            lblDireccion.setText(ctrlProveedor.getListaProveedores().getByIndex(cbxProveedor.getSelectedIndex()).getDireccionProveedor());
            ctrlProveedor.setProveedor(ctrlProveedor.getListaProveedores().getByIndex(indice));
        }
    }//GEN-LAST:event_cbxProveedorItemStateChanged

    /**
     * Evento para cargar la ventana de Comprar
     * @param evt evento de tipo mouseevent
     */
    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        VentanaComprar vc = new VentanaComprar(ctrlPersona);
        this.dispose();
        vc.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * Evento para cargar la ventana de Perfil
     * @param evt evento de tipo mouseevent
     */
    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, cp);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * Evento para cargar la ventana de FacturarCompra
     * @param evt evento de tipo mouseevent
     */
    private void jmFacturarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmFacturarCompraMouseClicked
        // TODO add your handling code here:
        VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, cp);
        vtFacturarCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmFacturarCompraMouseClicked

    /**
     * Evento para cargar la ventana de Producto
     * @param evt evento de tipo mouseevent
     */
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        VentanaProducto vp = new VentanaProducto(cp, ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * Evento para cargar la ventana de Kardex
     * @param evt evento de tipo mouseevent
     */
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        VentanaKardex ventana = new VentanaKardex(this.cp, this.ctrlPersona);
        this.dispose();
        ventana.show();
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * Evento para cargar la ventana de Registrar
     * @param evt evento de tipo mouseevent
     */
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, cp);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * Evento para cargar la ventana de Sistema
     * @param evt evento de tipo Sistema
     */
    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, cp);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu8MouseClicked

    private void cbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProveedorActionPerformed

    /**
     * Evento para cargar la ventana de agregarProveedor
     * @param evt evento de tipo actionEvent
     */
    private void btAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProveedorActionPerformed
        VentanaAgregarProveedor vtAgrProveedor = new VentanaAgregarProveedor(ctrlProveedor);
        vtAgrProveedor.setVisible(true);
        this.setEnabled(false);
        vtAgrProveedor.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowDeactivated(WindowEvent e) {
                
                cerrarVentanasSecundarias();
                cargarCBXProveedor();
            }
        });   
    }//GEN-LAST:event_btAgregarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFacturarCompras(new ControladorPersona(), new ControladorProducto()).setVisible(true);
            }
        });
    }
    
    /**
     * Metodo para cerrar las ventanas secundarias y mostrar esta
     */
    private void cerrarVentanasSecundarias()
    {
        this.setEnabled(true);
        this.toFront();
    }
    
    /**
     * Metodo para cargar los proveedores en el comboBox
     */
    
    private void cargarCBXProveedor()
    {
        cbxProveedor.removeAllItems();
        
        for (int i = 0; i < ctrlProveedor.getListaProveedores().length(); i++)
        {
            cbxProveedor.addItem(ctrlProveedor.getListaProveedores().getByIndex(i).getNombreProveedor() + " "  + ctrlProveedor.getListaProveedores().getByIndex(i).getApellidoProveedor());
        }
    }
    
    /**
     * Metodo para instanciar los datos de la factura
     */
    private void instanciarDatosFactura()
    {
        ctrlFacturaCompra.generarNumeroFactura();
        ctrlFacturaCompra.calcularFecha();
        
        DateFormat dfD = DateFormat.getDateInstance(DateFormat.SHORT);
        DateFormat dfH = DateFormat.getTimeInstance(DateFormat.MEDIUM);
        
        lblNroFactura.setText(ctrlFacturaCompra.getFactura().getNroFactura());
        lblFecha.setText(dfD.format(ctrlFacturaCompra.getFactura().getFecha()) + " " + dfH.format(ctrlFacturaCompra.getFactura().getFecha()));
    }
    
    /**
     * Metodo para Agregar una compra a la facturaCompra y a la tabla principal
     */
    private void agregarCompraTabla()
    {
        DefaultTableModel modelo=(DefaultTableModel) jtDetalleFactura.getModel();
        modelo.setRowCount(0);
        jtDetalleFactura.setModel(modelo);
        
        Object[] fila = new Object[4];
        
        for (int i = 0; i < ctrlFacturaCompra.getFactura().getListaDetalles().length(); i++)
        {
            fila[0] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getIdProducto();
            fila[1] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getCantidad();
            fila[2] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getPrecioUnitario();
            fila[3] = ctrlFacturaCompra.getFactura().getListaDetalles().getByIndex(i).getPrecioTotal();
            modelo.addRow(fila);
        }
        
        jtDetalleFactura.setModel(modelo);
        calcularCostos();
    }
    
    /**
     * Metodo para calcular los costos de las compras al proveedor
     */
    private void calcularCostos()
    {
        DecimalFormat dc = new DecimalFormat("##.##");
        
        ctrlFacturaCompra.setIva(0.12);
        lblSubtotal.setText(Double.toString(ctrlFacturaCompra.getFactura().getSubTotal()));
        lblIVA.setText(dc.format(ctrlFacturaCompra.getFactura().getIva()));
        lblTotal.setText(ctrlFacturaCompra.getFactura().getTotal().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCompra;
    private javax.swing.JButton btAgregarProveedor;
    private javax.swing.JButton btFacturar;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenu jmFacturarCompra;
    private javax.swing.JTable jtDetalleFactura;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIvaIndicador;
    private javax.swing.JLabel lblNroFactura;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
