/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFactura;
import Controlador.ControladorKardex;
import Controlador.ControladorPersona;
import Controlador.ControladorValoresPorDefecto;
import Controlador.EstructurasDinamicas.Lista;
import Controlador.ControladorProducto;
import Modelo.Enum.Color;
import Modelo.Enum.Prenda;
import Modelo.Enum.TipoPrenda;
import Modelo.Producto;
import Vista.ModeloTablas.ModeloTablaProductoCompra;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author jere_
 */
public class VentanaComprar extends javax.swing.JFrame {

    private ControladorProducto ctrlProducto; //ControladorProducto usado para llamar a los metodos de este
    private ModeloTablaProductoCompra modelo = new ModeloTablaProductoCompra();//ModeloTabla usado para mostrar el contenido en las tablas
    private ControladorPersona ctrlPersona;//ControladorProducto usado para llamar a los metodos de este
    private ControladorFactura ctrlFactura;//ControladorFactura usado para llamar a los metodos de este
    private ControladorValoresPorDefecto ctrlVPD;//ControladorValoresPorDefecto usado para llamar a los metodos de este
    private ControladorKardex ck = new ControladorKardex();//ControladorKardex usado para llamar a los metodos de este

    /**
     *Constructor de la ventana, usado para pasar la informacion de la persona que inicio sesion, entre ventanas
     * @param ctrlPersona el controladorPersona que contiene a la persona que inicio sesion
     */
    public VentanaComprar(ControladorPersona ctrlPersona) {
        initComponents();
        this.setLocationRelativeTo(null);
        ck.setListaKardex(ck.listar());
        ctrlProducto = new ControladorProducto();
        ctrlProducto.setProductos(ctrlProducto.listar());
        this.ctrlPersona = ctrlPersona;
        this.ctrlVPD = new ControladorValoresPorDefecto();
        ctrlFactura = new ControladorFactura(ctrlVPD.getVpd().getIVA());
        ctrlFactura.setPersona(ctrlPersona.getPersona());

        cbxCriterioBusqueda.removeAllItems();
        cargarTabla();
        cargarCombo();
        ocultarColumnaID(jtCarrito);
        ocultarColumnaID(jtListaProductos);

        DefaultTableModel modelo = (DefaultTableModel) jtCarrito.getModel();
        modelo.setRowCount(0);
        jtCarrito.setModel(modelo);

        ctrlFactura.getFactura();
        ctrlFactura.getFactura().setId(Integer.toUnsignedLong(ctrlPersona.getPersona().getFacturas().length() + 1));
        ctrlFactura.getFactura().setFecha(ctrlPersona.convertToDateViaInstant(LocalDate.now()));
        ctrlFactura.generar_nroFactura();

        jmComprar.setEnabled(false);
        comprobarRol();
        encabezadoColor();
    }

    /**
     * Metodo para cargar los comboBoxes de la ventana
     */
    private void cargarCombo() {
        cbxCriterioBusqueda.addItem("Marca");
        cbxCriterioBusqueda.addItem("Nombre");
        cbxCriterioBusqueda.addItem("Tipo Prenda");
        cbxCriterioBusqueda.addItem("Prenda");
        cbxCriterioBusqueda.addItem("Color");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtfBuscar = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        cbxCriterioBusqueda = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btAgregarCarrito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblProductoSelect = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarrito = new javax.swing.JTable();
        btFacturar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        txtfCantidad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmComprar = new javax.swing.JMenu();
        jmPerfil = new javax.swing.JMenu();
        jmFacturarCompra = new javax.swing.JMenu();
        jmAgregarProducto = new javax.swing.JMenu();
        jmKardex = new javax.swing.JMenu();
        jmRegistros = new javax.swing.JMenu();
        jmSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Nombre", "TipoPrenda", "Color", "Tipo", "Talla", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 597, 233));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupaIcono.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        txtfBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtfBuscar.setBorder(null);
        txtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBuscarActionPerformed(evt);
            }
        });
        txtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 112, 20));

        lblFoto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(0, 0, 0));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("IMAGEN");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 126, 154));

        cbxCriterioBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cbxCriterioBusqueda.setBorder(null);
        jPanel1.add(cbxCriterioBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 112, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Buscar por:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btAgregarCarrito.setBackground(new java.awt.Color(255, 255, 255));
        btAgregarCarrito.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btAgregarCarrito.setForeground(new java.awt.Color(0, 0, 0));
        btAgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoAgregarCarrito.png"))); // NOI18N
        btAgregarCarrito.setBorderPainted(false);
        btAgregarCarrito.setContentAreaFilled(false);
        btAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(btAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 60, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Producto Seleccionado: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));
        jPanel1.add(lblProductoSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 120, 20));

        jtCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Cantidad", "Precio", "PrecioTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCarrito.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarritoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCarrito);
        if (jtCarrito.getColumnModel().getColumnCount() > 0) {
            jtCarrito.getColumnModel().getColumn(0).setResizable(false);
            jtCarrito.getColumnModel().getColumn(1).setResizable(false);
            jtCarrito.getColumnModel().getColumn(2).setResizable(false);
            jtCarrito.getColumnModel().getColumn(3).setResizable(false);
            jtCarrito.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 422, 178));

        btFacturar.setBackground(new java.awt.Color(255, 255, 255));
        btFacturar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btFacturar.setForeground(new java.awt.Color(0, 0, 0));
        btFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facturarIcono.png"))); // NOI18N
        btFacturar.setBorderPainted(false);
        btFacturar.setContentAreaFilled(false);
        btFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturarActionPerformed(evt);
            }
        });
        jPanel1.add(btFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 40, 50));

        btRemover.setBackground(new java.awt.Color(255, 255, 255));
        btRemover.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btRemover.setForeground(new java.awt.Color(0, 0, 0));
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminarIcono.png"))); // NOI18N
        btRemover.setBorderPainted(false);
        btRemover.setContentAreaFilled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 40, 50));

        txtfCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtfCantidad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtfCantidad.setBorder(null);
        jPanel1.add(txtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 91, 20));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Comprar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprarIcono.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(328, 328, 328))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 940, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 90, 10));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 120, 10));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, 10));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 660, -1));

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 510, -1));

        jmComprar.setText("Comprar");
        jmComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmComprarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmComprar);

        jmPerfil.setText("Perfil");
        jmPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPerfilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmPerfil);

        jmFacturarCompra.setText("Abastecer");
        jmFacturarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmFacturarCompraMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmFacturarCompra);

        jmAgregarProducto.setText("Productos");
        jmAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAgregarProductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAgregarProducto);

        jmKardex.setText("Kardex");
        jmKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmKardexMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmKardex);

        jmRegistros.setText("Registros");
        jmRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRegistrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmRegistros);

        jmSistema.setText("Sistema");
        jmSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSistemaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para buscar productos basado en la busqueda binaria y simple de las vistas
     */
    private void buscar() {
        switch (cbxCriterioBusqueda.getSelectedIndex()) {
            case 0:
                ctrlProducto.setProducto(new Producto());
                ctrlProducto.getProducto().getMarca().setNombreMarca(txtfBuscar.getText().toLowerCase());
                modelo.setLista(ctrlProducto.getProductos().multipleSearch("marca", ctrlProducto.getProducto().getMarca()));
                break;
            case 1:
                modelo.setLista(ctrlProducto.getProductos().multipleSearch("nombre", txtfBuscar.getText().toLowerCase()));
                break;
            case 2:

                for (TipoPrenda t : TipoPrenda.values()) {
                    if (t.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("tipoPrenda", TipoPrenda.valueOf(t.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
            case 3:
                for (Prenda p : Prenda.values()) {
                    if (p.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("prenda", Prenda.valueOf(p.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
            case 4:
                for (Color c : Color.values()) {
                    if (c.toString().toLowerCase().startsWith(txtfBuscar.getText().toLowerCase())) {
                        modelo.setLista(ctrlProducto.getProductos().multipleSearch("color", Color.valueOf(c.toString())));
                        break;
                    }
                    modelo.setLista(new Lista());
                }
                break;
        }
    }
    private void txtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBuscarActionPerformed

    }//GEN-LAST:event_txtfBuscarActionPerformed

    /**
     * Evento para cargar la informacion del producto que el cliente selecciono en la lista de productos
     * @param evt Evento de mouseclicked
     */
    private void jtListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaProductosMouseClicked
        try 
        {
            generarImagen(jtListaProductos);
            Integer index = jtListaProductos.getSelectedRow();
            Integer id = ((Long) jtListaProductos.getValueAt(index, 0)).intValue();
            ctrlProducto.setProducto(ctrlProducto.getProductos().getByIndex(id - 1));
            lblProductoSelect.setText(ctrlProducto.getProducto().getNombre());
            jtCarrito.clearSelection();
        } 
        catch (Exception e) 
        {
        }
    }//GEN-LAST:event_jtListaProductosMouseClicked

    /**
     * Evento para actualizar las busquedas por cada letra que el cliente escribe en el campo de texto
     * @param evt Evento de tipo keyevent
     */
    private void txtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBuscarKeyReleased

        jtListaProductos.clearSelection();

        if (txtfBuscar.getText().isBlank()) {
            cargarTabla();
        } else {
            buscar();
            jtListaProductos.setModel(modelo);
            jtListaProductos.updateUI();
        }
    }//GEN-LAST:event_txtfBuscarKeyReleased

    /**
     * Evento para cargar la informacion del producto que el cliente selecciono de su carrito
     * @param evt evento de tipo mouseEvent
     */
    private void jtCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarritoMouseClicked
        jtListaProductos.clearSelection();
        generarImagen(jtCarrito);
    }//GEN-LAST:event_jtCarritoMouseClicked

    /**
     * Evento para agregar el producto seleccionado al carrito
     * @param evt evento de tipo actionEvent
     */
    private void btAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCarritoActionPerformed
    
        try 
        {
            if (jtListaProductos.getSelectedRow() == -1 || txtfCantidad.getText().isBlank())
            {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un producto y su cantidad");
            } 
            else 
            {
                if(ctrlProducto.getProducto().getStock() - Integer.valueOf(txtfCantidad.getText()) < 0)
                {
                    JOptionPane.showMessageDialog(null, "Lo sentimos, no hay suficiente stock del producto");
                }
                else
                {
                    DefaultTableModel modelo = (DefaultTableModel) jtCarrito.getModel();

                    Object[] fila = new Object[5];

                    fila[0] = ctrlProducto.getProducto().getId();
                    fila[1] = ctrlProducto.getProducto().getNombre();
                    fila[2] = txtfCantidad.getText();
                    fila[3] = ctrlProducto.getProducto().getPrecioVenta();
                    fila[4] = (ctrlProducto.getProducto().getPrecioVenta() * Integer.valueOf(txtfCantidad.getText()));
                    modelo.addRow(fila);
                    jtCarrito.setModel(modelo);
                }
                
            }
            registrarDetalle();
        }
        catch (ClassCastException e) {
        }
        
    }//GEN-LAST:event_btAgregarCarritoActionPerformed

    /**
     * Evento para remover un producto del carrito del cliente
     * @param evt evento de tipo ActionEvent
     */
    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed

        Integer index = jtCarrito.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Debe escoger un producto del carrito", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ctrlFactura.borrarDetalle((Long) jtCarrito.getValueAt(index, 0));
            DefaultTableModel modelotmp = (DefaultTableModel) jtCarrito.getModel();
            modelotmp.removeRow(index);
        }
        jtCarrito.clearSelection();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void jmComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmComprarMouseClicked

    }//GEN-LAST:event_jmComprarMouseClicked

    /**
     * Evento para cargar la ventana de facturarCompra
     * @param evt evento de tipo mouseEvent
     */
    private void jmFacturarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmFacturarCompraMouseClicked

        VentanaFacturarCompras vtFacturarCompra = new VentanaFacturarCompras(ctrlPersona, ctrlProducto);
        vtFacturarCompra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmFacturarCompraMouseClicked

    /**
     * Evento para generar la vista previa de la factura del cliente en base a su carrito
     * @param evt evento de tipo actionEvent
     */
    private void btFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturarActionPerformed

        ctrlFactura.calcularSubTotal();
        ctrlFactura.calcularIva();
        ctrlFactura.calcularTotal();
        VentanaFactura vtFactura = new VentanaFactura(null, true, ctrlPersona, ctrlFactura, ctrlProducto);
        vtFactura.setVisible(true);
        vtFactura.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setEnabled(false);
        vtFactura.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("hola");
                cerrarVentanasSecundarias();
                cargarTabla();
            }
        });
    }//GEN-LAST:event_btFacturarActionPerformed

    /**
     * Evento para cargar la ventana de Registros
     * @param evt evento de tipo mouseevent
     */
    private void jmRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRegistrosMouseClicked
        VentanaRegistro vtRegistrar = new VentanaRegistro(null, false, ctrlPersona, ctrlProducto);
        vtRegistrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmRegistrosMouseClicked

    /**
     * Evento para cargar la ventana de Perfil
     * @param evt evento de tipo mouseevent
     */
    private void jmPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPerfilMouseClicked
        VentanaPerfil vtPerfil = new VentanaPerfil(ctrlPersona, ctrlProducto);
        vtPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmPerfilMouseClicked

    /**
     * Evento para cargar la ventana de sistema
     * @param evt evento de tipo mouseevent
     */
    private void jmSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSistemaMouseClicked
        VentanaSistema vtSistema = new VentanaSistema(ctrlPersona, ctrlProducto);
        vtSistema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmSistemaMouseClicked

    /**
     * Evento para cargar la ventana de Productos
     * @param evt evento de tipo mouseevent
     */
    private void jmAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAgregarProductoMouseClicked
        VentanaProducto vp = new VentanaProducto(this.ctrlProducto, this.ctrlPersona);
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_jmAgregarProductoMouseClicked

    /**
     * Evento para cargar la ventana de Kardex
     * @param evt evento de tipo mouseevent
     */
    private void jmKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmKardexMouseClicked
        // TODO add your handling code here:
        VentanaKardex vk = new VentanaKardex(ctrlProducto, ctrlPersona);
        this.dispose();
        vk.setVisible(true);
    }//GEN-LAST:event_jmKardexMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaComprar(new ControladorPersona()).setVisible(true);
            }
        });
    }

    /**
     * Metodo para cargar la imagen del producto seleccionado
     * @param jt la tabla en la que se selecciono el producto a presentar
     */
    private void generarImagen(JTable jt) {
        Integer index = jt.getSelectedRow();
        Integer id = ((Long) jt.getValueAt(index, 0)).intValue();
        ImageIcon icon = ctrlProducto.getProductos().getByIndex(id - 1).getIcon();
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setText(null);
        lblFoto.setIcon(icono);
    }

    /**
     * Metodo para cargar los modelos de la tabla
     */
    private void cargarTabla() {
        modelo.setLista(ctrlProducto.getProductos());
        jtListaProductos.setModel(modelo);
        jtListaProductos.updateUI();
    }

    /**
     * Metodo para ocultar la columna id de una tabla
     * @param jt la tabla en la que se va a ocultar la columna id
     */
    
    private void ocultarColumnaID(JTable jt) {
        jt.getColumnModel().getColumn(0).setMaxWidth(0);
        jt.getColumnModel().getColumn(0).setMinWidth(0);
        jt.getColumnModel().getColumn(0).setPreferredWidth(0);
        jt.getColumnModel().getColumn(0).setResizable(false);
    }

    /**
     * Metodo para registrar el detalleFactura dentro del controladorFactura
     */
    private void registrarDetalle() {
        Integer cantidad = Integer.valueOf(txtfCantidad.getText().trim());
        ctrlFactura.cargarDetalleFactura(ctrlProducto.getProducto().getId(), ctrlProducto.getProducto(), cantidad, ctrlProducto.getProducto().getPrecioVenta(), (ctrlProducto.getProducto().getPrecioVenta()) * cantidad);
        ctrlFactura.guardarDetalleFactura();
    }

    /**
     * Metodo para cerrar las ventanas secundarias y que esta se vuelva a presentar
     */
    
    private void cerrarVentanasSecundarias() {
        this.setEnabled(true);
        this.toFront();
    }

    /**
     * Metodo para comprobar el rol del usuario
     */
    private void comprobarRol() {
        System.out.println("ComprobarRol: " + ctrlPersona.getPersona().getId_Rol().getNombreRol());
        if (ctrlPersona.getPersona().getId_Rol().getNombreRol().equals("cliente")) {
            jmFacturarCompra.setEnabled(false);
            jmFacturarCompra.setVisible(false);
            jmKardex.setEnabled(false);
            jmKardex.setVisible(false);
            jmRegistros.setEnabled(false);
            jmRegistros.setVisible(false);
            jmAgregarProducto.setEnabled(false);
            jmAgregarProducto.setVisible(false);
            jmSistema.setEnabled(false);
            jmSistema.setVisible(false);
        }

    }
    
    /**
     * Metodo para pintar el encabezado de las tablas
     */
    private void encabezadoColor()
    {
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new java.awt.Color(51, 153, 255));
        for (int i = 0; i < 9; i++) {
            if(i < 5)
            {
                TableColumn column = jtCarrito.getTableHeader().getColumnModel().getColumn(i);
                column.setHeaderRenderer(cellRenderer);
                cellRenderer.setHorizontalAlignment(cellRenderer.CENTER);
            }
            TableColumn column = jtListaProductos.getTableHeader().getColumnModel().getColumn(i);
            column.setHeaderRenderer(cellRenderer);
            cellRenderer.setHorizontalAlignment(cellRenderer.CENTER);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCarrito;
    private javax.swing.JButton btFacturar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox<String> cbxCriterioBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JMenu jmAgregarProducto;
    private javax.swing.JMenu jmComprar;
    private javax.swing.JMenu jmFacturarCompra;
    private javax.swing.JMenu jmKardex;
    private javax.swing.JMenu jmPerfil;
    private javax.swing.JMenu jmRegistros;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JTable jtCarrito;
    private javax.swing.JTable jtListaProductos;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblProductoSelect;
    private javax.swing.JTextField txtfBuscar;
    private javax.swing.JTextField txtfCantidad;
    // End of variables declaration//GEN-END:variables
}
