/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPersona;
import Modelo.Enum.TipoIdentif;
import java.awt.Dimension;

/**
 *
 * @author santiago-arg
 */
public class VentanaRegistrar extends javax.swing.JDialog {

    /**
     * Creates new form VentanaRegistrar
     */
    public VentanaRegistrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(new Dimension(459,475));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxTipoDeIdent = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtfIdentificacion = new javax.swing.JTextField();
        btRegistrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 85, 44, 16);
        getContentPane().add(txtfNombre);
        txtfNombre.setBounds(242, 82, 138, 22);

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 125, 44, 16);
        getContentPane().add(txtfApellido);
        txtfApellido.setBounds(242, 122, 138, 22);

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 167, 50, 16);
        getContentPane().add(txtfDireccion);
        txtfDireccion.setBounds(242, 165, 138, 22);

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 210, 36, 16);
        getContentPane().add(txtfCorreo);
        txtfCorreo.setBounds(242, 205, 138, 22);

        jLabel5.setText("Tipo de identificación");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 257, 114, 16);

        cbxTipoDeIdent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEDULA", "PASAPORTE", "RUC" }));
        getContentPane().add(cbxTipoDeIdent);
        cbxTipoDeIdent.setBounds(242, 254, 138, 22);

        jLabel6.setText("Identificación");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 308, 72, 16);
        getContentPane().add(txtfIdentificacion);
        txtfIdentificacion.setBounds(242, 305, 138, 22);

        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrar);
        btRegistrar.setBounds(260, 380, 76, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        
        ControladorPersona ctrlPersona = new ControladorPersona();
        
        ctrlPersona.getPersona().setNombres(txtfNombre.getText());
        ctrlPersona.getPersona().setApellidos(txtfApellido.getText());
        ctrlPersona.getPersona().setDireccion(txtfDireccion.getText());
        ctrlPersona.getPersona().setCorreo(txtfCorreo.getText());
        ctrlPersona.getPersona().setTipoDeIdentificacion(TipoIdentif.valueOf(cbxTipoDeIdent.getSelectedItem().toString()).toString());
        ctrlPersona.getPersona().setIdentificacion(txtfIdentificacion.getText());
        
        ctrlPersona.guardar(ctrlPersona.getPersona());
        
        System.out.println(ctrlPersona.listar().getByIndex(0).getNombres());
        
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistrar dialog = new VentanaRegistrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxTipoDeIdent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtfApellido;
    private javax.swing.JTextField txtfCorreo;
    private javax.swing.JTextField txtfDireccion;
    private javax.swing.JTextField txtfIdentificacion;
    private javax.swing.JTextField txtfNombre;
    // End of variables declaration//GEN-END:variables
}
